In [1]:
import numpy as np
import pandas as pd

In [2]:
acc = open('bash_scripts/SRR_Acc_List.txt', 'r')

In [3]:
cells = []
test = ['Gene_Id', 'SRR1974543']
test2 = ['SRR1974544']
for i in acc.readlines():
    cells.append(i.rstrip())
print(test)

['Gene_Id', 'SRR1974543']

In [4]:
df = pd.read_csv('counts_ncbi/SRR1974543/count.txt', sep='\t', header=0)
df

                         A1BG        0
0                    A1BG-AS1        0
1                        A1CF        0
2                         A2M        0
3                     A2M-AS1        0
4                       A2ML1        0
...                       ...      ...
43681            __no_feature  1088585
43682             __ambiguous    29380
43683         __too_low_aQual        0
43684           __not_aligned        0
43685  __alignment_not_unique    41694

[43686 rows x 2 columns]

In [5]:
df.columns = test
df.set_index('Gene_Id')

                        SRR1974543
Gene_Id
A1BG-AS1                         0
A1CF                             0
A2M                              0
A2M-AS1                          0
A2ML1                            0
...                            ...
__no_feature               1088585
__ambiguous                  29380
__too_low_aQual                  0
__not_aligned                    0
__alignment_not_unique       41694

[43686 rows x 1 columns]

In [6]:
df

                      Gene_Id  SRR1974543
0                    A1BG-AS1           0
1                        A1CF           0
2                         A2M           0
3                     A2M-AS1           0
4                       A2ML1           0
...                       ...         ...
43681            __no_feature     1088585
43682             __ambiguous       29380
43683         __too_low_aQual           0
43684           __not_aligned           0
43685  __alignment_not_unique       41694

[43686 rows x 2 columns]

In [7]:
for i in cells[1:]:
    tdf = pd.read_csv('/home/drt15/SRP/counts_ncbi/' + i + '/count.txt', sep='\t')
    name = ['Gene_Id', i]
    tdf.columns = name
    tdf.set_index('Gene_Id')  
    ext = tdf[i]
    df = df.join(ext)

In [8]:
df.head(50)

,Gene_Id,SRR1974543,SRR1974544,SRR1974545,SRR1974546,SRR1974547,SRR1974548,SRR1974549,SRR1974550,SRR1974551,...,SRR1974999,SRR1975000,SRR1975001,SRR1975002,SRR1975003,SRR1975004,SRR1975005,SRR1975006,SRR1975007,SRR1975008
0,A1BG-AS1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,A1CF,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,A2M,0,17,1,0,1,0,0,0,0,...,216,0,0,0,0,0,0,0,0,0
3,A2M-AS1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,A2ML1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,A2MP1,0,0,0,0,0,0,0,0,0,...,0,443,0,0,0,0,0,0,0,0
6,A3GALT2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,A4GALT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,A4GNT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,AA06,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,AAAS,1,0,0,0,23,0,4,0,0,...,0,0,0,0,0,0,20,81,0,0
11,AACS,0,0,0,19,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
12,AACSP1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,AADAC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,AADACL2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,AADACL2-AS1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,AADACL3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,AADACL4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,AADACP1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,AADAT,0,0,0,0,6,0,192,0,124,...,0,0,0,0,0,14,0,0,0,0
20,AAGAB,0,744,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,AAK1,301,213,0,25,12,0,2,5,6,...,1,496,44,7,803,0,5,510,1,0
22,AAMDC,0,0,6,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,21,0
23,AAMP,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,AANAT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,AAR2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,69,0,0,0
26,AARD,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,AARS1,0,7,161,106,16,0,7,1,0,...,0,22,0,253,0,0,0,0,101,0
28,AARS1P1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,AARS2,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
30,AARSD1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
31,AARSD1P1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,AASDH,0,0,0,24,113,0,0,0,3,...,7,0,34,13,0,5,0,0,0,0
33,AASDHPPT,0,0,0,48,5,2,84,0,2,...,9,0,0,0,0,26,0,1099,0,0
34,AASS,179,0,1,0,52,1244,1389,3,58,...,0,652,0,0,0,0,0,0,0,0
35,AATBC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
36,AATF,0,0,43,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37,AATK,14,0,23,4,4,1,7,0,21,...,0,0,0,0,0,0,0,0,0,0
38,ABALON,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,ABAT,0,464,0,8,181,47,0,0,49,...,0,163,0,0,0,7,0,1,0,0
40,ABCA1,1013,474,9,33,0,107,0,0,16,...,0,413,1,232,0,0,0,0,371,0
41,ABCA10,0,0,0,0,145,0,0,13,0,...,0,0,0,0,0,0,0,0,0,0
42,ABCA11P,0,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,29,0
43,ABCA12,2,0,0,0,1,0,0,0,45,...,0,0,0,0,0,0,0,0,0,0
44,ABCA13,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
45,ABCA17P,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
46,ABCA2,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
47,ABCA3,0,0,0,0,0,0,0,0,0,...,35,0,0,0,0,0,0,0,0,1
48,ABCA4,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49,ABCA5,0,786,0,1,374,8,0,104,25,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df.set_index('Gene_Id')

,SRR1974543,SRR1974544,SRR1974545,SRR1974546,SRR1974547,SRR1974548,SRR1974549,SRR1974550,SRR1974551,SRR1974552,...,SRR1974999,SRR1975000,SRR1975001,SRR1975002,SRR1975003,SRR1975004,SRR1975005,SRR1975006,SRR1975007,SRR1975008
Gene_Id,,,,,,,,,,,,,,,,,,,,,
A1BG-AS1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A1CF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A2M,0,17,1,0,1,0,0,0,0,0,...,216,0,0,0,0,0,0,0,0,0
A2M-AS1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
A2ML1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
__no_feature,1088585,1338774,1233297,1615224,1227566,1613661,863771,1905668,1142759,901715,...,1282444,919170,454959,1015392,648903,522938,803602,713566,1123132,881931
__ambiguous,29380,30754,28921,22332,32692,23584,22824,30553,19253,31523,...,13957,12903,14107,13065,15073,14632,16846,20259,19240,16572
__too_low_aQual,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
__not_aligned,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
__alignment_not_unique,41694,56815,33346,46906,53441,51423,35188,53325,40045,45829,...,33523,33352,32972,36663,33053,38840,46945,44239,57273,45586

In [10]:
df.to_csv('ncbi_final_counts.csv')